name: CI

on:
  push:
    branches:
      - main  # Run on pushes to the 'main' branch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov httpx

      - name: Run unit tests
        run: |
          pytest --cov=. --cov-report term-missing --cov-report xml --cov-report html --junitxml=junit/unit_test_results.xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml

      - name: Run integration tests
        run: |
          pytest -s test_integration.py --junitxml=junit/integration_test_results.xml


      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: junit
          path: junit